### ISSUE TITLE
How to display game assets data?

### ISSUE THREAD

**Issue by phuctohoang** [sousa-andre/lcu-driver#24]
Response
`"squarePortraitPath": "/lol-game-data/assets/v1/champion-icons/10.png",`
How to display it on tkinter or something else?

**Comment by sousa-andre** [comment]
You can find the icons [here ](https://raw.communitydragon.org/latest/plugins/rcp-be-lol-game-data/global/default/v1/champion-icons/).
I'm closing this issue since it is not related with the library. For questions related to the LCU API itselfyou can use [this](https://discord.com/invite/riotgamesdevrel) discord.
